apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /var/www
              name: app-storage
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
